"""
ALGENZA Video Engine Package
"""
from .config import (
    BRAND_NAME, BRAND_TAG, BRAND_SLOGAN, BRAND_URL, BRAND_DISPLAY_URL,
    COLORS, ASPECT_RATIOS, DEFAULT_ASPECT, DEFAULT_FPS, DEFAULT_SAMPLE_RATE,
    PRODUCTS, METRICS
)
